import * as THREE from 'three';
import {GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
import {OrbitControls}from'three/addons/controls/OrbitControls.js';
import{createWindFarmControls}from'./wind_farm_controls.mjs';
const scene=new THREE.Scene();scene.background=new THREE.Color('#e5ebea');scene.fog=new THREE.Fog('#e5ebea',420,950);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;document.body.prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,1800);camera.position.set(-220,155,285);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,55,0);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
scene.add(new THREE.HemisphereLight(0xdcefff,0x7b8c83,3));const sun=new THREE.DirectionalLight(0xffeedb,3);sun.position.set(-100,180,70);scene.add(sun);
const $=s=>document.querySelector(s);let farm,selected=null,goal=null,request;
function focus(info,wide=false){const size=Math.max(info.size.x,info.size.y,info.size.z);goal={target:info.center.clone(),position:info.center.clone().add(new THREE.Vector3(-1,.55,1.4).normalize().multiplyScalar(size*(wide?2:2.7)+5))};}
async function select(id){selected=id;farm.selectTurbine(id);focus(farm.getFocusTarget(id),true);$('#title').textContent=id==='turbine_1'?'Турбина 01':'Турбина 02';$('#status').textContent='Выбрана '+id;$('#error').textContent='';$('#data').textContent='Загрузка данных API…';request?.abort();request=new AbortController();try{const r=await fetch(`/api/turbines/${id}/details`,{signal:request.signal});if(!r.ok||!r.headers.get('content-type')?.includes('application/json'))throw Error('Данные API пока недоступны');const data=await r.json();$('#data').textContent=JSON.stringify(data.current??{},null,2);if(Number.isFinite(data.current?.wind_speed))farm.applyTurbineState(id,{windSpeed:data.current.wind_speed});}catch(e){if(e.name!=='AbortError')$('#data').textContent='API не подключён. Модель доступна для осмотра.';}}
try{const gltf=await new GLTFLoader().loadAsync('../models/wind_farm.glb');scene.add(gltf.scene);farm=createWindFarmControls(THREE,gltf);farm.setRotorSpeed('turbine_1',.35);farm.setRotorSpeed('turbine_2',.27);$('#status').textContent='Модель загружена · 2 турбины';window.windFarm={farm,scene,gltf};}catch(e){$('#error').textContent=e.message;}
for(const b of document.querySelectorAll('[data-id]'))b.onclick=()=>farm&&select(b.dataset.id);
for(const b of document.querySelectorAll('[data-c]'))b.onclick=()=>{if(!farm)return;if(!selected)select('turbine_1');farm.inspectComponent(selected,b.dataset.c);focus(farm.getComponentFocusTarget(selected,b.dataset.c));};
$('#speed').oninput=e=>{if(farm)farm.setRotorSpeed(selected??'turbine_1',+e.target.value);};
$('#overview').onclick=()=>{farm?.resetInspection();goal={target:new THREE.Vector3(0,55,0),position:new THREE.Vector3(-220,155,285)};};
$('#reset').onclick=()=>{farm?.reset();selected=null;request?.abort();$('#title').textContent='Обзор станции';$('#data').textContent='';$('#speed').value=0;$('#overview').click();};
let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!farm||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);for(const hit of ray.intersectObjects(scene.children,true)){const id=farm.getTurbineId(hit.object);if(id){select(id);break;}}});orbit.addEventListener('start',()=>goal=null);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const dt=clock.getDelta();farm?.update(dt);if(goal){const a=1-Math.exp(-dt*5);camera.position.lerp(goal.position,a);orbit.target.lerp(goal.target,a);if(camera.position.distanceTo(goal.position)<.02)goal=null;}orbit.update();renderer.render(scene,camera);});
