import {createTwin} from './twin.js';
import {createAssistantPanel} from './assistant-panel.js';
import {createOverviewMotion} from './overview-motion.js';
const revealOverview = createOverviewMotion();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={id:'turbine_1',hours:24,mode:'replay',history:'power',data:null,historical:null,request:0};let twin;
const assistant=createAssistantPanel(()=>state,result=>{if(state.data){state.data={...state.data,...result};render();}});
const number=(v,d=2)=>Number.isFinite(v)?v.toFixed(d):'—';
const date=v=>v?new Intl.DateTimeFormat('en-GB',{timeZone:'Etc/GMT-5',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))+' · Astana UTC+05':'—';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,options);if(!r.ok){const body=await r.json().catch(()=>({}));throw Error(typeof body.detail==='string'?body.detail:`API error ${r.status}`);}return r.json();}
const sections=['overview','analytics','agent'];
function setActiveSection(id){$$('[data-view]').forEach(link=>{const active=link.dataset.view===id;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});}
function navigate(){const route=location.hash.slice(1),inApp=sections.includes(route),enteringApp=inApp&&$('#application').hidden;$('#landing').hidden=inApp;$('#application').hidden=!inApp;$$('.view').forEach(v=>v.hidden=false);if(inApp){if(enteringApp)revealOverview();setActiveSection(route);requestAnimationFrame(()=>document.getElementById(route).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}));if(state.data)assistant.activate();}}
addEventListener('hashchange',navigate);$$('[data-launch]').forEach(b=>b.onclick=()=>location.hash='overview');$('#home-brand').onclick=()=>location.hash='landing';navigate();
let scrollTick=false;
addEventListener('scroll',()=>{if(scrollTick||$('#application').hidden)return;scrollTick=true;requestAnimationFrame(()=>{const offset=$('.app-header').getBoundingClientRect().height+80;let active='overview';for(const id of sections)if(document.getElementById(id).getBoundingClientRect().top<=offset)active=id;setActiveSection(active);scrollTick=false;});},{passive:true});
function chart(values,{low,high,min=0,max=1,timestamps}={}){
 if(!values.length||!values.some(Number.isFinite))return '<p class="error-state">No observations available.</p>';
 const x=i=>40+670*i/Math.max(1,values.length-1),y=v=>12+190*(1-(v-min)/(max-min||1));
 const path=arr=>{let pen=false;return arr.map((v,i)=>{if(!Number.isFinite(v)){pen=false;return '';}const p=`${pen?'L':'M'}${x(i)} ${y(v)}`;pen=true;return p;}).join(' ');};
 const grid=Array.from({length:5},(_,i)=>`<line x1="40" y1="${12+i*47.5}" x2="710" y2="${12+i*47.5}" stroke="#55718a" opacity=".25"/><text x="0" y="${16+i*47.5}" fill="#5a74a0" font-size="11">${number(max-(max-min)*i/4,1)}</text>`).join('');
 const labels=Array.from({length:5},(_,i)=>{const n=Math.round((values.length-1)*i/4);const label=timestamps?new Intl.DateTimeFormat('en-CA',{timeZone:'Etc/GMT-5',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(timestamps[n])):`+${n}h`;return `<text x="${x(n)}" y="230" text-anchor="${i===0?'start':i===4?'end':'middle'}" fill="#5a74a0" font-size="11">${label}</text>`;}).join('');
 const band=low&&high?`<path d="${path(high)} ${low.map((_,j)=>{const i=low.length-1-j;return `L${x(i)} ${y(low[i])}`;}).join(' ')} Z" fill="#2858ff" opacity=".2"/>`:'';
 return `<svg viewBox="0 0 720 240" role="img" aria-label="${timestamps?'Historical daily observations':'Hourly forecast, normalized power'}">${grid}${labels}${band}<path d="${path(values)}" fill="none" stroke="#1243ff" stroke-width="2"/></svg>`;
}
function renderTimeline(){const p=state.data?.forecast[+$('#timeline-slider').value];if(!p)return;$('#detail-wind').textContent=number(p.wind_speed,1)+' m/s';$('#detail-temp').textContent=number(p.temperature,1)+' °C';$('#timeline-time').textContent=date(p.timestamp);$('#timeline-wind').textContent=number(p.wind_speed,1)+' m/s';$('#timeline-temp').textContent=number(p.temperature,1)+' °C';$('#timeline-power').textContent=number(p.predicted_power);twin?.apply(state.id,p);}
function renderHistory(){const points=state.historical?.points??[],key={power:'power',wind:'wind_speed',temp:'temperature'}[state.history],values=points.map(p=>p[key]),valid=values.filter(Number.isFinite);const svg=chart(values,{min:state.history==='temp'?Math.min(0,...valid):0,max:state.history==='power'?1:Math.max(1,...valid),timestamps:points.map(p=>p.timestamp)});$('#history-chart').innerHTML=svg;$('#analytics-history').innerHTML=svg;$('#analytics-history-title').textContent=`Historical ${key.replace('_',' ')}`;$$('[data-history]').forEach(b=>b.classList.toggle('active',b.dataset.history===state.history));}
function renderAgent(a){if(!a)return;$('#hero-agent').textContent=a.status;for(const id of ['detailed-status'])$('#'+id).textContent=a.status;const steps=a.steps??[];$('#overview-steps').innerHTML=steps.map(s=>`<li><span>${escape(s.state)}</span><time>${escape(date(s.timestamp))}</time></li>`).join('');$('#agent-pipeline').innerHTML=steps.map((s,i)=>`<article><span>${i+1}</span><div><h3>${escape(s.state)}</h3><p>${escape(s.message)}</p></div></article>`).join('');$('#agent-log').innerHTML=steps.map(s=>`<div><time>${escape(date(s.timestamp))}</time><span>${escape(s.message)}</span></div>`).join('');}
function render(){const d=state.data;if(!d)return;const c=d.current;$('#turbine-title').textContent=d.name;$('#coords').textContent=`${d.latitude.toFixed(6)}, ${d.longitude.toFixed(6)}`;$('#current-power').textContent=number(c?.power);$('#current-wind').textContent=number(c?.wind_speed,1);$('#current-temp').textContent=number(c?.temperature,1);$('#hero-wind').textContent=number(c?.wind_speed,1)+' m/s';$('#hero-temp').textContent=number(c?.temperature,1)+' °C';$('#scada-time').textContent=date(c?.timestamp);$('.app-meta small').textContent='Generated: '+date(d.generated_at);const arr=d.forecast;
 const svg=chart(arr.map(p=>p.predicted_power),{low:arr.map(p=>p.lower_power),high:arr.map(p=>p.upper_power)});$('#analytics-forecast').innerHTML=svg;$('#detail-forecast').innerHTML=svg;$('#expected').textContent=number(arr.reduce((sum,p)=>sum+p.predicted_power,0)/arr.length);const peak=arr.reduce((a,b)=>a.predicted_power>b.predicted_power?a:b);$('#peak').textContent=number(peak.predicted_power);$('#peak-time').textContent=date(peak.timestamp);$('#gauge-value').textContent=number(peak.predicted_power);$('#gauge-time').textContent=date(peak.timestamp);$('#peak-gauge-arc').setAttribute('stroke-dasharray',`${Math.max(0,Math.min(1,peak.predicted_power))*100} 100`);$$('.summary-tile .metric-ring').slice(0,2).forEach((ring,i)=>ring.style.setProperty('--progress',`${(i?peak.predicted_power:arr.reduce((sum,p)=>sum+p.predicted_power,0)/arr.length)*360}deg`));$('#range-label').textContent=`(${state.hours}h)`;$('#analytics-range').textContent=state.hours;$('#timeline-slider').max=arr.length-1;$('#timeline-slider').disabled=false;$('#timeline-slider').value=Math.min(+$('#timeline-slider').value,arr.length-1);
 const weather=arr.filter((_,i)=>i%6===0);$('#weather-mini').innerHTML=weather.map(p=>`<div><small>${escape(date(p.timestamp))}</small><b>${number(p.temperature,1)}°</b><small>${number(p.wind_speed,1)} m/s</small></div>`).join('');$('#weather-list').innerHTML=weather.map(p=>`<div><strong>${escape(date(p.timestamp))}</strong><span>${number(p.wind_speed,1)} m/s · ${number(p.temperature,1)}°C</span></div>`).join('');
 $('#data-notice').textContent=[...(d.warnings??[]),...(d.assessment?.issues??[]).map(i=>i.message)].join(' · ');renderTimeline();renderAgent(d.agent);$('#copilot-context').textContent=`${state.id} · ${state.hours} ч · ${state.mode} · ${date(d.forecast_origin)}`;assistant.update(d);
}
function clearForecast(){$('#peak-gauge-arc').setAttribute('stroke-dasharray','0 100');for(const id of ['gauge-value','gauge-time','detail-wind','detail-temp'])$('#'+id).textContent='—';$$('.metric-ring').forEach(r=>r.style.removeProperty('--progress'));state.data=null;assistant.clear();twin?.stop();$('#timeline-slider').disabled=true;for(const id of ['analytics-forecast','detail-forecast','weather-mini','weather-list'])$('#'+id).textContent='Loading forecast…';for(const id of ['hero-wind','hero-temp','current-power','current-wind','current-temp','coords','expected','peak','peak-time','timeline-time','timeline-wind','timeline-temp','timeline-power','scada-time'])$('#'+id).textContent='—';for(const id of ['overview-steps','agent-pipeline','agent-log'])$('#'+id).textContent='Waiting for backend…';}
async function load(recalculate=false){$('#copilot-answer').textContent='Запустите агента для выбранной турбины и горизонта.';$('#copilot-tools').textContent='';$('#copilot-status').textContent='Готов к запуску';$('#copilot-error').hidden=true;const token=++state.request,id=state.id,mode=state.mode,hours=state.hours;clearForecast();$('#hero-horizon').textContent=hours+' hours';$('#weather-horizon').textContent='Next '+hours+'h';$('#hero-agent').textContent='Loading';$('#detailed-status').textContent='Loading';$('#data-notice').textContent='';$('#connection-status').textContent='Loading backend data…';$$('[data-turbine]').forEach(b=>{const active=`turbine_${+b.dataset.turbine+1}`===id;b.classList.toggle('chosen',active);b.classList.toggle('selected',active);});$$('[data-range]').forEach(b=>b.classList.toggle('active',+b.dataset.range===hours));twin?.select(id);$('#turbine-title').textContent=id.replace('_',' ');const buttons=[$('#run-agent'),$('#refresh-data')];buttons.forEach(b=>b.disabled=true);
 const historyPromise=api(`/api/history/${id}`).then(d=>{if(token===state.request){state.historical=d;renderHistory();}}).catch(()=>{if(token===state.request){state.historical=null;renderHistory();}});
 const timer=setInterval(()=>api('/api/agent/status').then(d=>{if(token===state.request)renderAgent(d.agents[id]);}).catch(()=>{}),1000);
 try{if(recalculate)await api('/api/forecast/recalculate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({turbine_id:id,hours,mode})});const d=await api(`/api/turbines/${id}/details?hours=${hours}&mode=${mode}`);if(token!==state.request)return;state.data=d;render();$('#connection-status').textContent='API connected · '+mode;}catch(e){if(token===state.request){$('#connection-status').textContent='Forecast unavailable';$('#data-notice').textContent=e.message;for(const id of ['analytics-forecast'])$('#'+id).textContent='Forecast unavailable. Use Refresh forecast to retry.';}}finally{clearInterval(timer);await historyPromise;if(token===state.request)buttons.forEach(b=>b.disabled=false);}}
function select(id){if(state.id===id)return;state.id=id;load();}
$$('[data-turbine]').forEach(b=>b.onclick=()=>select(`turbine_${+b.dataset.turbine+1}`));$$('[data-range]').forEach(b=>b.onclick=()=>{if(state.hours===+b.dataset.range)return;state.hours=+b.dataset.range;load();});$$('[data-history]').forEach(b=>b.onclick=()=>{state.history=b.dataset.history;renderHistory();});$('#timeline-slider').oninput=renderTimeline;$('#forecast-mode').onchange=e=>{state.mode=e.target.value;load();};$('#refresh-data').onclick=()=>load();$('#run-agent').onclick=()=>load(true);$('#view-execution').onclick=()=>location.hash='agent';
createTwin(select,selection=>assistant.inspect(selection)).then(result=>{twin=result;twin?.select(state.id);renderTimeline();});load();

$('#agent-export').onclick=$('#export-forecast').onclick=()=>{location.href=`/api/export/${state.id}?hours=${state.hours}&mode=${state.mode}`;};
async function renderValidation(){
 try{const data=await api('/api/validation/metrics');$('#validation-evidence').innerHTML='<div class="evidence-table-wrap"><table><thead><tr><th>Турбина</th><th>MAE модели</th><th>MAE базового</th><th>Снижение MAE</th><th>Покрытие интервала</th></tr></thead><tbody>'+Object.entries(data.turbines).map(([id,r])=>`<tr><td>${escape(id)}</td><td>${number(r.model.mae,4)}</td><td>${number(r.baseline.mae,4)}</td><td>${number((1-r.model.mae/r.baseline.mae)*100,1)}%</td><td>${number(r.interval_coverage*100,1)}%</td></tr>`).join('')+'</tbody></table></div>';}
 catch(e){$('#validation-evidence').textContent=e.message;}
}
async function renderMonitor(){try{const d=await api('/api/agent/status'),m=d.monitor;$('#monitor-status').textContent=m.enabled?`Включено · каждые ${m.interval_seconds/60} мин · ${m.status}${m.last_check?' · '+date(m.last_check):''}`:'Монитор выключен в настройках сервера';}catch{$('#monitor-status').textContent='Монитор недоступен';}}
$('#check-updates').onclick=async()=>{const b=$('#check-updates');b.disabled=true;$('#monitor-status').textContent='Проверяю погоду и входные данные…';try{await api('/api/agent/check-updates',{method:'POST'});await renderMonitor();}catch(e){$('#monitor-status').textContent=e.message;}finally{b.disabled=false;}};
$('#copilot-form').onsubmit=async e=>{
 e.preventDefault();const button=$('#run-copilot'),token=state.request;
 button.disabled=true;$$('[data-agent-task]').forEach(b=>b.disabled=true);$('#copilot-status').textContent='Агент работает…';$('#copilot-answer').textContent='Проверяю данные, рассчитываю прогноз и оцениваю риски. Обычно это занимает до минуты.';$('#copilot-tools').textContent='';$('#copilot-error').hidden=true;
 const body={turbine_id:state.id,hours:state.hours,mode:state.mode,message:$('#copilot-prompt').value};
 try{const d=await api('/api/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(token!==state.request)return;
  $('#copilot-status').textContent=d.status==='completed'?'Завершено · OpenAI':d.status==='degraded'?'Резервный расчёт':'Ошибка расчёта';
  $('#copilot-answer').textContent=d.answer;
  if(d.llm_error){$('#copilot-error').hidden=false;$('#copilot-error').textContent=d.llm_error;}
  $('#copilot-tools').innerHTML=d.tools.map(t=>`<article><strong>${escape(t.tool)} · ${escape(t.status)}</strong><time>${escape(date(t.timestamp))}</time><pre>${escape(JSON.stringify(t.result,null,2))}</pre></article>`).join('');
  if(d.forecast&&state.data){state.data={...state.data,...d.forecast};render();}
 }catch(error){if(token===state.request){$('#copilot-status').textContent='Ошибка';$('#copilot-answer').textContent=error.message;}}finally{button.disabled=false;$$('[data-agent-task]').forEach(b=>b.disabled=false);}
};
$$('[data-agent-task]').forEach(button=>button.onclick=()=>{if($('#run-copilot').disabled)return;$('#copilot-prompt').value=button.dataset.agentTask;$('#copilot-form').requestSubmit();$('#copilot-title').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});
renderValidation();renderMonitor();setInterval(()=>{if(!document.hidden)renderMonitor();},30000);

// Stay on Overview when returning to the top of the dashboard.
document.querySelector('[data-overview-top]').addEventListener('click',event=>{event.preventDefault();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
